version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ${HOME}/Documentos/Docker/gerenciamento-loja/PostgreSQL:/var/lib/postgresql/data
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  
  jsf-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-compose
    ports:
      - "8081:8080"
        
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16432:80"
    depends_on:
      - postgres-compose

      
